FROM node:lts-alpine3.23
WORKDIR /usr/src/app

# Define ARG and ENV
ARG APP_VERSION=1.0.0
ENV GREETING="Hello from Docker!"

COPY sources/package.json ./
RUN npm install
COPY sources/ .
EXPOSE 8081

# Use ARG during build
RUN echo "Version: $APP_VERSION" > version.txt

CMD ["npm", "start"]
